# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            Herbal Access Project
tagline:          'Growing medicine for communities with barriers to herbal access'
description:      'Urbancrafting health justice by growing herbs for folks serving Native, POC, Trans, Houseless, Farm Worker, Low Income & other important communities!'
url:              http://herbalaccessproject.github.io

author:
  name:           'Dandy Lion'
  url:            mailto://herbalaccessprojectnw@gmail.com

paginate:         0

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/herbalaccessproject/herbalaccessproject.github.io
